# -*- coding: utf-8 -*-
"""MultiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o80vuNZfGIQ_DmeCK3Q1VZCej4rwV7ii
"""

import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    raise RuntimeError("Set the GOOGLE_API_KEY environment variable before running this script.")
os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model='gemini-3.5-flash-lite',
    temperature=0,
)

question = input("Ask Something?")

response = llm.invoke(question)
answer = response.content

if isinstance(answer, list):
    answer = "\n".join(item["text"] for item in answer)

print("\n" + "="*60)
print(question)
print("\n" + "="*60)
print(answer)
